CREATE TABLE USERS (
                       email VARCHAR(30) NOT NULL PRIMARY KEY,
                       student_id VARCHAR(7) NOT NULL CHECK (student_id ~ '^[0-9]{7}$'),
                       address VARCHAR(100),
                       password VARCHAR NOT NULL,
                       date_of_birth DATE NOT NULL,
                       first_name VARCHAR(50) NOT NULL,
                       last_name VARCHAR(50) NOT NULL,
                       role VARCHAR(12)
);
CREATE TABLE FOLLOWERS (
                           student_email VARCHAR(30) NOT NULL,
                           follower_email VARCHAR(30) NOT NULL,
                           PRIMARY KEY (student_email, follower_email),
                           FOREIGN KEY (student_email) REFERENCES USERS(email) ON DELETE CASCADE,
                           FOREIGN KEY (follower_email) REFERENCES USERS(email) ON DELETE CASCADE
);
CREATE TABLE POSTS (
                       post_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                       email VARCHAR(30) NOT NULL,
                       content VARCHAR NOT NULL,
                       post_created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       FOREIGN KEY (email) REFERENCES USERS(email) ON DELETE CASCADE
);

CREATE TABLE POST_LIKES (
                            post_id INT NOT NULL,
                            post_liked_user VARCHAR(30) NOT NULL,
                            PRIMARY KEY (post_id,post_liked_user),
                            post_likes_created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            FOREIGN KEY (post_id) REFERENCES POSTS(post_id) ON DELETE CASCADE,
                            FOREIGN KEY (post_liked_user) REFERENCES USERS(email) ON DELETE CASCADE
);

CREATE TABLE POST_COMMENTS (
                               post_id INT NOT NULL,
                               post_comment_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               PRIMARY KEY (post_id,post_comment_id),
                               post_comment_user VARCHAR(30) NOT NULL,
                               post_comment_text VARCHAR NOT NULL,
                               post_comment_created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               FOREIGN KEY (post_id) REFERENCES POSTS(post_id) ON DELETE CASCADE,
                               FOREIGN KEY (post_comment_user) REFERENCES USERS(email) ON DELETE CASCADE
);
